# Generated by Django 5.0.6 on 2026-07-13 07:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Agent ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='角色名称')),
                ('age', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(1)], verbose_name='年龄')),
                ('biography', models.TextField(blank=True, default='', help_text='角色的背景故事描述，用于初始化 System Prompt', verbose_name='背景故事')),
                ('mbti_type', models.CharField(choices=[('ISTJ', '内向-实感-思考-判断 (检查员)'), ('ISFJ', '内向-实感-情感-判断 (守护者)'), ('INFJ', '内向-直觉-情感-判断 (提倡者)'), ('INTJ', '内向-直觉-思考-判断 (建筑师)'), ('ISTP', '内向-实感-思考-感知 (鉴赏家)'), ('ISFP', '内向-实感-情感-感知 (探险家)'), ('INFP', '内向-直觉-情感-感知 (调停者)'), ('INTP', '内向-直觉-思考-感知 (逻辑学家)'), ('ESTP', '外向-实感-思考-感知 (企业家)'), ('ESFP', '外向-实感-情感-感知 (表演者)'), ('ENFP', '外向-直觉-情感-感知 (竞选者)'), ('ENTP', '外向-直觉-思考-感知 (辩论家)'), ('ESTJ', '外向-实感-思考-判断 (总经理)'), ('ESFJ', '外向-实感-情感-判断 (领事)'), ('ENFJ', '外向-直觉-情感-判断 (主人公)'), ('ENTJ', '外向-直觉-思考-判断 (指挥官)')], default='INFP', help_text='16型人格，影响决策系数和行为倾向', max_length=4, verbose_name='MBTI 人格类型')),
                ('status', models.CharField(choices=[('idle', '空闲/待命'), ('moving', '移动中'), ('interacting', '交互中/社交中'), ('sleeping', '睡眠中'), ('busy', '忙碌（执行计划）')], default='idle', max_length=20, verbose_name='当前状态')),
                ('energy', models.FloatField(default=100.0, help_text='0-100，影响行动意愿和决策倾向', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='精力值')),
                ('social_energy', models.FloatField(default=100.0, help_text='社交后降低，独处时恢复', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='社交能量')),
                ('pos_x', models.FloatField(default=0.0, verbose_name='X 坐标')),
                ('pos_y', models.FloatField(default=0.0, verbose_name='Y 坐标')),
                ('pos_z', models.FloatField(default=0.0, verbose_name='Z 坐标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '智能体',
                'verbose_name_plural': '智能体',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MBTIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti_type', models.CharField(choices=[('ISTJ', '内向-实感-思考-判断 (检查员)'), ('ISFJ', '内向-实感-情感-判断 (守护者)'), ('INFJ', '内向-直觉-情感-判断 (提倡者)'), ('INTJ', '内向-直觉-思考-判断 (建筑师)'), ('ISTP', '内向-实感-思考-感知 (鉴赏家)'), ('ISFP', '内向-实感-情感-感知 (探险家)'), ('INFP', '内向-直觉-情感-感知 (调停者)'), ('INTP', '内向-直觉-思考-感知 (逻辑学家)'), ('ESTP', '外向-实感-思考-感知 (企业家)'), ('ESFP', '外向-实感-情感-感知 (表演者)'), ('ENFP', '外向-直觉-情感-感知 (竞选者)'), ('ENTP', '外向-直觉-思考-感知 (辩论家)'), ('ESTJ', '外向-实感-思考-判断 (总经理)'), ('ESFJ', '外向-实感-情感-判断 (领事)'), ('ENFJ', '外向-直觉-情感-判断 (主人公)'), ('ENTJ', '外向-直觉-思考-判断 (指挥官)')], max_length=4, unique=True, verbose_name='MBTI类型')),
                ('label', models.CharField(max_length=32, verbose_name='人格标签')),
                ('core_drive', models.CharField(help_text='例如：‘追求效率与秩序’ / ‘探索新可能性’', max_length=256, verbose_name='核心驱动力')),
                ('communication_style', models.CharField(help_text='例如：‘直接了当，注重事实’ / ‘委婉含蓄，关注感受’', max_length=256, verbose_name='沟通风格')),
                ('decision_style', models.CharField(help_text='例如：‘逻辑分析优先’ / ‘以人为本’', max_length=256, verbose_name='决策风格')),
                ('social_initiative', models.FloatField(default=0.5, help_text='主动发起社交的概率系数', verbose_name='社交主动性')),
                ('plan_adherence', models.FloatField(default=0.7, help_text='遵守原定计划的程度，越高越不易被打断', verbose_name='计划遵循度')),
                ('curiosity', models.FloatField(default=0.5, help_text='探索新事物/新交互的倾向', verbose_name='好奇心')),
                ('emotionality', models.FloatField(default=0.5, help_text='决策受情绪影响的程度', verbose_name='情绪化程度')),
                ('talkativeness', models.FloatField(default=0.5, help_text='对话中生成内容的长度和丰富度', verbose_name='健谈程度')),
            ],
            options={
                'verbose_name': 'MBTI 行为矩阵',
                'verbose_name_plural': 'MBTI 行为矩阵',
                'ordering': ['mbti_type'],
            },
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='计划日期')),
                ('generation_type', models.CharField(choices=[('base', '基础日程'), ('llm_dynamic', 'LLM 动态覆盖'), ('player_intervention', '玩家干预')], default='base', max_length=20, verbose_name='生成方式')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='agents.agent', verbose_name='关联 Agent')),
            ],
            options={
                'verbose_name': '每日日程表',
                'verbose_name_plural': '每日日程表',
                'ordering': ['-date'],
                'unique_together': {('agent', 'date', 'generation_type')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('activity', models.CharField(max_length=256, verbose_name='活动描述')),
                ('location', models.CharField(blank=True, default='', max_length=128, verbose_name='活动地点')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('in_progress', '执行中'), ('completed', '已完成'), ('interrupted', '被打断'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('interruption_reason', models.TextField(blank=True, default='', verbose_name='打断原因')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('interrupted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interruptions', to='agents.agent', verbose_name='打断者')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agents.dailyschedule', verbose_name='所属日程')),
            ],
            options={
                'verbose_name': '日程项',
                'verbose_name_plural': '日程项',
                'ordering': ['schedule', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SocialInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('greeting', '打招呼'), ('conversation', '对话'), ('joint_activity', '共同活动'), ('conflict', '冲突')], max_length=20, verbose_name='交互类型')),
                ('trigger_context', models.TextField(blank=True, default='', verbose_name='触发上下文')),
                ('summary', models.TextField(blank=True, default='', verbose_name='交互摘要')),
                ('interrupted_initiator_plan', models.BooleanField(default=False, verbose_name='是否打断发起方计划')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='交互时间')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='持续分钟数')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_interactions', to='agents.agent', verbose_name='发起方')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interactions', to='agents.agent', verbose_name='接收方')),
            ],
            options={
                'verbose_name': '社交交互记录',
                'verbose_name_plural': '社交交互记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
