# Generated by Django 5.0.6 on 2026-07-14 01:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='城市名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='城市描述')),
                ('pos_x', models.FloatField(default=0.0, verbose_name='X 偏移')),
                ('pos_y', models.FloatField(default=0.0, verbose_name='Y 偏移')),
                ('width', models.FloatField(default=200.0, verbose_name='城市宽度')),
                ('height', models.FloatField(default=200.0, verbose_name='城市高度')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'ordering': ['world', 'name'],
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='世界名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='世界描述')),
                ('width', models.FloatField(default=1000.0, verbose_name='世界宽度')),
                ('height', models.FloatField(default=1000.0, verbose_name='世界高度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '世界',
                'verbose_name_plural': '世界',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='区域名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='区域描述')),
                ('district_type', models.CharField(choices=[('residential', '住宅区'), ('commercial', '商业区'), ('entertainment', '娱乐区'), ('park', '公园/绿地'), ('education', '教育区'), ('industrial', '工业区'), ('administrative', '行政区'), ('transportation', '交通枢纽')], default='residential', max_length=20, verbose_name='区域类型')),
                ('pos_x', models.FloatField(default=0.0, verbose_name='X 偏移')),
                ('pos_y', models.FloatField(default=0.0, verbose_name='Y 偏移')),
                ('width', models.FloatField(default=50.0, verbose_name='区域宽度')),
                ('height', models.FloatField(default=50.0, verbose_name='区域高度')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='world.city', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'ordering': ['city', 'name'],
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='场景名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='场景描述')),
                ('pos_x', models.FloatField(default=0.0, verbose_name='X 坐标')),
                ('pos_y', models.FloatField(default=0.0, verbose_name='Y 坐标')),
                ('width', models.FloatField(default=5.0, verbose_name='场景宽度')),
                ('height', models.FloatField(default=5.0, verbose_name='场景高度')),
                ('max_occupancy', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最大容纳人数')),
                ('current_occupancy', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='当前人数')),
                ('function_tags', models.CharField(blank=True, default='', help_text='如：eat,socialize 表示可用于餐饮和社交', max_length=256, verbose_name='功能标签（逗号分隔）')),
                ('interactables', models.JSONField(blank=True, default=list, help_text='场景内的物品/设备列表', verbose_name='可交互对象')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='world.district', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '场景',
                'verbose_name_plural': '场景',
                'ordering': ['district', 'name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.AddField(
            model_name='city',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='world.world', verbose_name='所属世界'),
        ),
        migrations.CreateModel(
            name='WorldEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64, verbose_name='事件类型')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='附加数据')),
                ('radius', models.FloatField(default=10.0, help_text='在此半径内的 Agent 能感知到该事件', verbose_name='影响半径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='事件时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='world.scene', verbose_name='发生场景')),
            ],
            options={
                'verbose_name': '世界事件',
                'verbose_name_plural': '世界事件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('world', 'name')},
        ),
        migrations.CreateModel(
            name='AgentPosition',
            fields=[
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='position', serialize=False, to='agents.agent', verbose_name='Agent')),
                ('pos_x', models.FloatField(default=0.0, verbose_name='精确 X 坐标')),
                ('pos_y', models.FloatField(default=0.0, verbose_name='精确 Y 坐标')),
                ('heading', models.FloatField(default=0.0, verbose_name='朝向角度')),
                ('speed', models.FloatField(default=1.0, verbose_name='移动速度')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='位置更新时间')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupants', to='world.scene', verbose_name='所在场景')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_positions', to='world.world', verbose_name='所在世界')),
            ],
            options={
                'verbose_name': 'Agent 位置',
                'verbose_name_plural': 'Agent 位置',
                'indexes': [models.Index(fields=['world', 'scene'], name='world_agent_world_i_a6fc20_idx')],
            },
        ),
    ]
