# Generated by Django 5.0.6 on 2026-07-14 02:20

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(choices=[('episodic', '情景记忆'), ('semantic', '语义记忆'), ('reflective', '反思记忆'), ('procedural', '程序记忆')], default='episodic', max_length=20, verbose_name='记忆类型')),
                ('content', models.TextField(verbose_name='记忆内容')),
                ('summary', models.CharField(blank=True, default='', max_length=512, verbose_name='记忆摘要')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True, verbose_name='向量嵌入')),
                ('importance', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='重要性')),
                ('recency_score', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='近因性分数')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记忆创建时间')),
                ('accessed_at', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
                ('status', models.CharField(choices=[('active', '活跃'), ('decaying', '衰减中'), ('archived', '已归档'), ('compressed', '已压缩')], default='active', max_length=20, verbose_name='记忆状态')),
                ('source', models.CharField(blank=True, default='', max_length=64, verbose_name='记忆来源')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='agents.agent', verbose_name='所属 Agent')),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='agents.socialinteraction', verbose_name='关联社交交互')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='world.scene', verbose_name='关联场景')),
            ],
            options={
                'verbose_name': '记忆条目',
                'verbose_name_plural': '记忆条目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='流名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='流描述')),
                ('stream_type', models.CharField(choices=[('daily', '每日流'), ('social', '社交流'), ('quest', '任务流'), ('reflection', '反思流')], default='daily', max_length=20, verbose_name='流类型')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True, verbose_name='流向量嵌入')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_streams', to='agents.agent', verbose_name='所属 Agent')),
            ],
            options={
                'verbose_name': '记忆流',
                'verbose_name_plural': '记忆流',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryStreamOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.memoryentry')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.memorystream')),
            ],
            options={
                'verbose_name': '记忆流顺序',
                'verbose_name_plural': '记忆流顺序',
                'ordering': ['stream', 'order'],
            },
        ),
        migrations.AddField(
            model_name='memorystream',
            name='memories',
            field=models.ManyToManyField(blank=True, related_name='streams', through='memory.MemoryStreamOrder', to='memory.memoryentry', verbose_name='包含的记忆'),
        ),
        migrations.AddIndex(
            model_name='memoryentry',
            index=models.Index(fields=['agent', 'memory_type'], name='memory_memo_agent_i_f30079_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryentry',
            index=models.Index(fields=['agent', '-importance'], name='memory_memo_agent_i_7e6944_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryentry',
            index=models.Index(fields=['agent', 'status'], name='memory_memo_agent_i_b2f129_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memorystreamorder',
            unique_together={('stream', 'memory')},
        ),
    ]
